---
abstract: 'Perl class for reading/writing DCMTK dcmqrscp configuration file.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.16
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.08
  Perl6::Slurp: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dicom-DCMTK-DCMQRSCP-Config
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.05
  Error::Pure: 0.16
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dicom-DCMTK-DCMQRSCP-Config
  homepage: https://github.com/tupinek/Dicom-DCMTK-DCMQRSCP-Config
  license: http://opensource.org/licenses/BSD-3-Clause
  repository: git://github.com/tupinek/Dicom-DCMTK-DCMQRSCP-Config
version: 0.02
